import time
import pandas as pd


def book_Flight():
    print(f'Welcome To Book A Flight Section {Name}')
    print('----------------------------------------')
    time.sleep(1)
    print('Here we have available airlines:\n1) PIA\n2) AirBlue\n3) Shaheen Airline\n4) Serena Airline\n5) Jinnah Airline\n')


def pia_Airline():
    time.sleep(1)
    print('PIA Airline Selected.')
    time.sleep(1)
    print('Kindly wait while we checking..')
    time.sleep(2)
    print('-------------------------------------------------------------------')
    print('Here is the chart you can see:\n')
    df = pd.read_csv('Timings_Data/pia_time.csv')
    print(df)
    print('We have availability to:\n1) Lahore\n2) Islamabad\n3) Peshawar\n4) Balochistan')
    ask3 = int(input('Select: '))
    if ask3 == 1 or ask3 == 2 or ask3 == 3 or ask3 == 4:
        nic_num = input('Enter Your NIC Number: ')
        nic_name = input('Your Full Name: ')
        print('Limit of passengers only 5')
        nic_passengers = int(input('Number of Total Passengers: '))
        if nic_passengers == 1:
            print('1 Passenger Confirmed..')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.9235 ')
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting PIA Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting PIA Service, Thanks :)')
        elif nic_passengers == 2:
            print('2 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*2)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting PIA Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting PIA Service, Thanks :)')
        elif nic_passengers == 3:
            print('3 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*3)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting PIA Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting PIA Service, Thanks :)')
        elif nic_passengers == 4:
            print('4 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*4)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting PIA Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting PIA Service, Thanks :)')
        elif nic_passengers == 5:
            print('5 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*5)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting PIA Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting PIA Service, Thanks :)')
        else:
            print('___________________________________________________')
            print('Sorry sir you can not select more than the limit...')
            print('___________________________________________________')
            time.sleep(1)


def blue_Airline():
    time.sleep(1)
    print('AirBlue Airline Selected.')
    time.sleep(1)
    print('Kindly wait while we checking..')
    time.sleep(2)
    print('-------------------------------------------------------------------')
    print('Here is the chart you can see:\n')
    df = pd.read_csv('Timings_Data/blue_time.csv')
    print(df)
    print('We have availability to:\n1) Lahore\n2) Islamabad\n3) Peshawar\n4) Balochistan')
    ask3 = int(input('Select: '))
    if ask3 == 1 or ask3 == 2 or ask3 == 3 or ask3 == 4:
        nic_num = input('Enter Your NIC Number: ')
        nic_name = input('Your Full Name: ')
        print('Limit of passengers only 5')
        nic_passengers = int(input('Number of Total Passengers: '))
        if nic_passengers == 1:
            print('1 Passenger Confirmed..')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.9235 ')
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting AirBlue Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting AirBlue Service, Thanks :)')
        elif nic_passengers == 2:
            print('2 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*2)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting AirBlue Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting AirBlue Service, Thanks :)')
        elif nic_passengers == 3:
            print('3 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*3)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting AirBlue Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting AirBlue Service, Thanks :)')
        elif nic_passengers == 4:
            print('4 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*4)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting AirBlue Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting AirBlue Service, Thanks :)')
        elif nic_passengers == 5:
            print('5 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*5)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting AirBlue Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting AirBlue Service, Thanks :)')
        else:
            print('___________________________________________________')
            print('Sorry sir you can not select more than the limit...')
            print('___________________________________________________')


def shaheen_Airline():
    time.sleep(1)
    print('Shaheen Airline Selected.')
    time.sleep(1)
    print('Kindly wait while we checking..')
    time.sleep(2)
    print('-------------------------------------------------------------------')
    print('Here is the chart you can see:\n')
    df = pd.read_csv('Timings_Data/shaheen_time.csv')
    print(df)
    print('We have availability to:\n1) Lahore\n2) Islamabad\n3) Peshawar\n4) Balochistan')
    ask3 = int(input('Select: '))
    if ask3 == 1 or ask3 == 2 or ask3 == 3 or ask3 == 4:
        nic_num = input('Enter Your NIC Number: ')
        nic_name = input('Your Full Name: ')
        print('Limit of passengers only 5')
        nic_passengers = int(input('Number of Total Passengers: '))
        if nic_passengers == 1:
            print('1 Passenger Confirmed..')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.9235 ')
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Shaheen Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Shaheen Airline Service, Thanks :)')
        elif nic_passengers == 2:
            print('2 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*2)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Shaheen Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Shaheen Airline Service, Thanks :)')
        elif nic_passengers == 3:
            print('3 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*3)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Shaheen Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Shaheen Airline Service, Thanks :)')
        elif nic_passengers == 4:
            print('4 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*4)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Shaheen Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Shaheen Airline Service, Thanks :)')
        elif nic_passengers == 5:
            print('5 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*5)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Shaheen Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Shaheen Airline Service, Thanks :)')
        else:
            print('___________________________________________________')
            print('Sorry sir you can not select more than the limit...')
            print('___________________________________________________')


def serena_Airline():
    time.sleep(1)
    print('Serena Airline Selected.')
    time.sleep(1)
    print('Kindly wait while we checking..')
    time.sleep(2)
    print('-------------------------------------------------------------------')
    print('Here is the chart you can see:\n')
    df = pd.read_csv('Timings_Data/serena_time.csv')
    print(df)
    print('We have availability to:\n1) Lahore\n2) Islamabad\n3) Peshawar\n4) Balochistan')
    ask3 = int(input('Select: '))
    if ask3 == 1 or ask3 == 2 or ask3 == 3 or ask3 == 4:
        nic_num = input('Enter Your NIC Number: ')
        nic_name = input('Your Full Name: ')
        print('Limit of passengers only 5')
        nic_passengers = int(input('Number of Total Passengers: '))
        if nic_passengers == 1:
            print('1 Passenger Confirmed..')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.9235 ')
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Serena Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Serena Airline Service, Thanks :)')
        elif nic_passengers == 2:
            print('2 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*2)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Serena Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Serena Airline Service, Thanks :)')
        elif nic_passengers == 3:
            print('3 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*3)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Serena Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Serena Airline Service, Thanks :)')
        elif nic_passengers == 4:
            print('4 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*4)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Serena Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Serena Airline Service, Thanks :)')
        elif nic_passengers == 5:
            print('5 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*5)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Serena Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Serena Airline Service, Thanks :)')
        else:
            print('___________________________________________________')
            print('Sorry sir you can not select more than the limit...')
            print('___________________________________________________')


def jinnah_Airline():
    time.sleep(1)
    print('Jinnah Airline Selected.')
    time.sleep(1)
    print('Kindly wait while we checking..')
    time.sleep(2)
    print('-------------------------------------------------------------------')
    print('Here is the chart you can see:\n')
    df = pd.read_csv('Timings_Data/jinnah_time.csv')
    print(df)
    print('We have availability to:\n1) Lahore\n2) Islamabad\n3) Peshawar\n4) Balochistan')
    ask3 = int(input('Select: '))
    if ask3 == 1 or ask3 == 2 or ask3 == 3 or ask3 == 4:
        nic_num = input('Enter Your NIC Number: ')
        nic_name = input('Your Full Name: ')
        print('Limit of passengers only 5')
        nic_passengers = int(input('Number of Total Passengers: '))
        if nic_passengers == 1:
            print('1 Passenger Confirmed..')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.9235 ')
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Jinnah Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Jinnah Airline Service, Thanks :)')
        elif nic_passengers == 2:
            print('2 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*2)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Jinnah Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Jinnah Airline Service, Thanks :)')
        elif nic_passengers == 3:
            print('3 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*3)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Jinnah Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Jinnah Airline Service, Thanks :)')
        elif nic_passengers == 4:
            print('4 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*4)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Serena Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Jinnah Airline Service, Thanks :)')
        elif nic_passengers == 5:
            print('5 Passengers Confirmed')
            print('Per passenger price is 9235.Rs So,\n')
            print('______________________')
            print('Total Price = Rs.', 9235*5)
            print('______________________')
            print(
                'Payment Nakad/Credit Card?\nPress 1 for Nakad & Press 2 for Credit Payment')
            ask4 = int(input())
            if ask4 == 1:
                time.sleep(2)
                print('Kindly take out this recipt and go to the counter #125')
                time.sleep(2)
                print('Thanks for selecting Jinnah Airline Service, Thanks :)')
                time.sleep(2)
            elif ask4 == 2:
                print('Kindly Enter Your Bank Id & Digital Code.')
                bank_id = input('Bank Id: ')
                bank_code = input('Bank Code: ')
                print('Please Wait...')
                time.sleep(1)
                print('Confirming...')
                time.sleep(2)
                print('---------------------------------------------')
                print('Payment Done, Take Out the recipt as a proof.')
                print('---------------------------------------------')
                time.sleep(2)
                print('Thanks for selecting Jinnah Airline Service, Thanks :)')
        else:
            print('___________________________________________________')
            print('Sorry sir you can not select more than the limit...')
            print('___________________________________________________')


# these are the little data of booked tickets
ticket_numbers = {4578, 6767, 3534, 8756, 1223, 6578, 7842, 4557}

print('Welcome to Jinnah International Airport Karchi')
print('----------------------------------------------')
print('جناح انٹرنیشنل ایئرپورٹ')
print('----------------------------------------------')

print('Please Enter Your Name & Pass Number: ')
Name = input('Name: ')
Pass = int(input('Pass No: '))

time.sleep(0.5)
print('Please Wait While We Checking...')
time.sleep(1.5)
print('Confirming..')
time.sleep(1)
print('Confirmed.')


print('-------------------------------------------------------------------')

while True:
    print('جناح انٹرنیشنل ایئرپورٹ')
    print('Here are the options, which one you wanna try: \n')
    print('-------------------------------------------------------------------')
    print('1) Book A Flight\n2) Check A Flight\n3) Cancel A Flight\n4) Exit\n')
    print('-------------------------------------------------------------------')
    ask1 = int(input('Select: '))
    if ask1 == 1:
        time.sleep(1)
        book_Flight()
        ask2 = input('Which One do You Want To Book? --> ').lower()
        if ask2 == '1':
            pia_Airline()
        elif ask2 == '2':
            blue_Airline()
        elif ask2 == '3':
            shaheen_Airline()
        elif ask2 == '4':
            serena_Airline()
        elif ask2 == '5':
            jinnah_Airline()
        else:
            print('Sorry Currently this airline not available, Thank You.')
    elif ask1 == 2:
        print('Welcome To Check A Flight Section.')
        time.sleep(1)
        print('Please be patient....')
        time.sleep(2)
        df2 = pd.read_csv('Airport_Data/airportdata.csv')
        print(df2)
        time.sleep(3)
        print('----------------------------------------------------------')
        print('To Check Particular Flight, Contact Our Service Stop #1464')
        time.sleep(3)
    elif ask1 == 3:
        print('Welcome To Cancel A Flight Section.')
        e_name = input('Enter Your NIC name: ')
        e_ticketnum = int(input('Enter Your Ticket Number: '))
        if e_ticketnum in ticket_numbers:
            time.sleep(2)
            print('Successfully Cancelled Your Ticket.')
            time.sleep(2)
        else:
            time.sleep(2)
            print('That Ticket Was never booked. Thank You :)')
            time.sleep(2)
    elif ask1 == 4:
        continue
    else:
        print('Wrong Command..')
